-- For the dynamic table of weapon slings, this table adds long guns that won't accept slings. Designed for sawed offs that remove sling mounts

VFESilencerBlacklist = {
	"Base.DoubleBarrelShotgun",
	"Base.DoubleBarrelShotgunSawnoff",
	"Base.DoubleBarrelShotgunSawnoffNoStock",
	"Base.MK23SOCOM",
	"Base.CAR15D",
	"Base.CAR15DFolded",
	"Base.ShotgunSilent",
	"Base.MK2SD",
	"Base.M60MMG",
	"Base.AssaultRifleMasterkey",
	"Base.AssaultRifleMasterkeyShotgun",
	"Base.M2400_Shotgun",
	"Base.M2400_Rifle",
}

VFECraftedSilencerBlacklist = {
	"Base.Shotgun",
	"Base.Shotgun2",
	"Base.ShotgunSawnoff",
	"Base.Spas12",
	"Base.Spas12Folded",
	"Base.ShotgunSemi",
	"Base.ShotgunSemi2",
    "Base.ShotgunSawnoffNoStock",
	"Base.DoubleBarrelShotgun",
	"Base.DoubleBarrelShotgunSawnoff",
	"Base.DoubleBarrelShotgunSawnoffNoStock",
	"Base.Revolver_Long",
	"Base.Revolver_Short",
	"Base.Revolver",
	"Base.MK23SOCOM",
	"Base.CAR15D",
	"Base.CAR15DFolded",
	"Base.ShotgunSilent",
	"Base.MK2SD",
	"Base.M60MMG",
	"Base.AssaultRifleMasterkey",
	"Base.AssaultRifleMasterkeyShotgun",
	"Base.M2400_Shotgun",
	"Base.M2400_Rifle",
}