-- ProceduralDistributions
require "Items/ProceduralDistributions"

-- SKL.PowderedMilk
table.insert(ProceduralDistributions.list["BakeryKitchenBaking"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["BakeryKitchenBaking"].items, 10);
table.insert(ProceduralDistributions.list["BreakRoomCounter"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["BreakRoomCounter"].items, 5);
table.insert(ProceduralDistributions.list["BreakRoomShelves"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["BreakRoomShelves"].items, 5);
table.insert(ProceduralDistributions.list["CrepeKitchenBaking"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["CrepeKitchenBaking"].items, 10);
table.insert(ProceduralDistributions.list["GigamartBakingMisc"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["GigamartBakingMisc"].items, 10);
table.insert(ProceduralDistributions.list["GigamartDryGoods"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["GigamartDryGoods"].items, 5);
table.insert(ProceduralDistributions.list["KitchenBaking"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["KitchenBaking"].items, 6);
table.insert(ProceduralDistributions.list["KitchenBreakfast"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["KitchenBreakfast"].items, 5);
table.insert(ProceduralDistributions.list["KitchenDryFood"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["KitchenDryFood"].items, 5);
table.insert(ProceduralDistributions.list["MexicanKitchenBaking"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["MexicanKitchenBaking"].items, 20);
table.insert(ProceduralDistributions.list["PizzaKitchenBaking"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["PizzaKitchenBaking"].items, 10);
table.insert(ProceduralDistributions.list["PrisonCellRandom"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["PrisonCellRandom"].items, 4);
table.insert(ProceduralDistributions.list["StoreKitchenBaking"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["StoreKitchenBaking"].items, 10);
table.insert(ProceduralDistributions.list["StoreKitchenCafe"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["StoreKitchenCafe"].items, 8);
table.insert(ProceduralDistributions.list["CrateCannedFood"].items, "SKL.PowderedMilk");
table.insert(ProceduralDistributions.list["CrateCannedFood"].items, 8);

-- SKL.YogurtCulture
table.insert(ProceduralDistributions.list["BakeryKitchenFreezer"].items, "SKL.YogurtCulture");
table.insert(ProceduralDistributions.list["BakeryKitchenFreezer"].items, 20);
table.insert(ProceduralDistributions.list["BakeryKitchenFridge"].items, "SKL.YogurtCulture");
table.insert(ProceduralDistributions.list["BakeryKitchenFridge"].items, 10);
table.insert(ProceduralDistributions.list["CafeKitchenFridge"].items, "SKL.YogurtCulture");
table.insert(ProceduralDistributions.list["CafeKitchenFridge"].items, 4);
table.insert(ProceduralDistributions.list["CrepeKitchenFridge"].items, "SKL.YogurtCulture");
table.insert(ProceduralDistributions.list["CrepeKitchenFridge"].items, 4);
table.insert(ProceduralDistributions.list["FreezerGeneric"].items, "SKL.YogurtCulture");
table.insert(ProceduralDistributions.list["FreezerGeneric"].items, 2);
table.insert(ProceduralDistributions.list["FreezerRich"].items, "SKL.YogurtCulture");
table.insert(ProceduralDistributions.list["FreezerRich"].items, 3);
table.insert(ProceduralDistributions.list["FridgeGeneric"].items, "SKL.YogurtCulture");
table.insert(ProceduralDistributions.list["FridgeGeneric"].items, 0.8);
table.insert(ProceduralDistributions.list["FridgeOther"].items, "SKL.YogurtCulture");
table.insert(ProceduralDistributions.list["FridgeOther"].items, 10);
table.insert(ProceduralDistributions.list["FridgeRich"].items, "SKL.YogurtCulture");
table.insert(ProceduralDistributions.list["FridgeRich"].items, 1);
table.insert(ProceduralDistributions.list["StoreKitchenBaking"].items, "SKL.YogurtCulture");
table.insert(ProceduralDistributions.list["StoreKitchenBaking"].items, 6);
table.insert(ProceduralDistributions.list["GigamartBakingMisc"].items, "SKL.YogurtCulture");
table.insert(ProceduralDistributions.list["GigamartBakingMisc"].items, 6);
table.insert(ProceduralDistributions.list["KitchenBaking"].items, "SKL.YogurtCulture");
table.insert(ProceduralDistributions.list["KitchenBaking"].items, 4);
table.insert(ProceduralDistributions.list["KitchenBreakfast"].items, "SKL.YogurtCulture");
table.insert(ProceduralDistributions.list["KitchenBreakfast"].items, 4);


-- SKL.Strainer
table.insert(ProceduralDistributions.list["BakeryKitchenBaking"].junk, "SKL.Strainer");
table.insert(ProceduralDistributions.list["BakeryKitchenBaking"].junk, 50);
table.insert(ProceduralDistributions.list["CrepeKitchenBaking"].junk, "SKL.Strainer");
table.insert(ProceduralDistributions.list["CrepeKitchenBaking"].junk, 50);
table.insert(ProceduralDistributions.list["GigamartPots"].items, "SKL.Strainer");
table.insert(ProceduralDistributions.list["GigamartPots"].items, 8);
table.insert(ProceduralDistributions.list["ItalianKitchenBaking"].junk, "SKL.Strainer");
table.insert(ProceduralDistributions.list["ItalianKitchenBaking"].junk, 75);
table.insert(ProceduralDistributions.list["JaysKitchenBaking"].junk, "SKL.Strainer");
table.insert(ProceduralDistributions.list["JaysKitchenBaking"].junk, 75);
table.insert(ProceduralDistributions.list["KitchenPots"].items, "SKL.Strainer");
table.insert(ProceduralDistributions.list["KitchenPots"].items, 6);
table.insert(ProceduralDistributions.list["MexicanKitchenBaking"].junk, "SKL.Strainer");
table.insert(ProceduralDistributions.list["MexicanKitchenBaking"].junk, 50);
table.insert(ProceduralDistributions.list["PizzaKitchenBaking"].junk, "SKL.Strainer");
table.insert(ProceduralDistributions.list["PizzaKitchenBaking"].junk, 30);
table.insert(ProceduralDistributions.list["StoreKitchenBaking"].items, "SKL.Strainer");
table.insert(ProceduralDistributions.list["StoreKitchenBaking"].items, 10);
table.insert(ProceduralDistributions.list["StoreKitchenPots"].items, "SKL.Strainer");
table.insert(ProceduralDistributions.list["StoreKitchenPots"].items, 8);

-- SKL.DairyCookingMag
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "SKL.DairyCookingMag");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "SKL.DairyCookingMag");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["KitchenBook"].items, "SKL.DairyCookingMag");
table.insert(ProceduralDistributions.list["KitchenBook"].items, 0.5);
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "SKL.DairyCookingMag");
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 1);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "SKL.DairyCookingMag");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.1);
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "SKL.DairyCookingMag");
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.1);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "SKL.DairyCookingMag");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 0.5);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "SKL.DairyCookingMag");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "SKL.DairyCookingMag");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);