
local function CustomCandyTweakRecipes()

    --custom
    
	
	local item = ScriptManager.instance:getItem("SapphCooking.SaucepanwithMeltedChocolate")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:4;SapphCooking.MacaronRed:4;SapphCooking.MacaronBlue:4;SapphCooking.MacaronGreen:4;SapphCooking.MacaronYellow:4;SapphCooking.MacaronPurple:4;SapphCooking.Cake_Chocolate:5;SapphCooking.Cake_Carrot:5;SapphCooking.Cake_BlackForest:5;SapphCooking.Cake_RedVelvet:5;SapphCooking.Cake_Strawberry:5;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.WhiteChocolate")
	if item then
		item:getTags():add("Chocolate")
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:4;SapphCooking.MacaronRed:4;SapphCooking.MacaronBlue:4;SapphCooking.MacaronGreen:4;SapphCooking.MacaronYellow:4;SapphCooking.MacaronPurple:4;SapphCooking.Cake_Chocolate:5;SapphCooking.Cake_Carrot:5;SapphCooking.Cake_BlackForest:5;SapphCooking.Cake_RedVelvet:5;SapphCooking.Cake_Strawberry:5;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2")
	end

    local item = ScriptManager.instance:getItem("SapphCooking.Syrup_Chocolate")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:4;SapphCooking.MacaronRed:4;SapphCooking.MacaronBlue:4;SapphCooking.MacaronGreen:4;SapphCooking.MacaronYellow:4;SapphCooking.MacaronPurple:4;SapphCooking.Cake_Chocolate:5;SapphCooking.Cake_Carrot:5;SapphCooking.Cake_BlackForest:5;SapphCooking.Cake_RedVelvet:5;SapphCooking.Cake_Strawberry:5;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.CornCob:2;SapphCooking.LasagnaEvolved:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.FrenchToastEvolved:2;SapphCooking.BowlSorbet:2;SapphCooking.BlenderShake:2;SapphCooking.CocktailMix:2;SapphCooking.SpringrollEvolved:2;SapphCooking.ArrozLecheEvolved:2;SapphCooking.ShavedIceEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.CoffeeThermosEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:1;SapphCooking.YakisobaEvolved:1;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Syrup_Strawberry")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:4;SapphCooking.MacaronRed:4;SapphCooking.MacaronBlue:4;SapphCooking.MacaronGreen:4;SapphCooking.MacaronYellow:4;SapphCooking.MacaronPurple:4;SapphCooking.Cake_Chocolate:5;SapphCooking.Cake_Carrot:5;SapphCooking.Cake_BlackForest:5;SapphCooking.Cake_RedVelvet:5;SapphCooking.Cake_Strawberry:5;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.CornCob:2;SapphCooking.LasagnaEvolved:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.FrenchToastEvolved:2;SapphCooking.BowlSorbet:2;SapphCooking.BlenderShake:2;SapphCooking.CocktailMix:2;SapphCooking.SpringrollEvolved:2;SapphCooking.ArrozLecheEvolved:2;SapphCooking.ShavedIceEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.CoffeeThermosEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:1;SapphCooking.YakisobaEvolved:1;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Syrup_Caramel")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:4;SapphCooking.MacaronRed:4;SapphCooking.MacaronBlue:4;SapphCooking.MacaronGreen:4;SapphCooking.MacaronYellow:4;SapphCooking.MacaronPurple:4;SapphCooking.Cake_Chocolate:5;SapphCooking.Cake_Carrot:5;SapphCooking.Cake_BlackForest:5;SapphCooking.Cake_RedVelvet:5;SapphCooking.Cake_Strawberry:5;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.CornCob:2;SapphCooking.LasagnaEvolved:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.FrenchToastEvolved:2;SapphCooking.BowlSorbet:2;SapphCooking.BlenderShake:2;SapphCooking.CocktailMix:2;SapphCooking.SpringrollEvolved:2;SapphCooking.ArrozLecheEvolved:2;SapphCooking.ShavedIceEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.CoffeeThermosEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:1;SapphCooking.YakisobaEvolved:1;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2")
	end

    local item = ScriptManager.instance:getItem("SapphCooking.PeanutButter_Sachet")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.FrenchToastEvolved:2;SapphCooking.BowlSorbet:2;SapphCooking.WokRoastVeg:2;SapphCooking.BlenderShake:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.CocktailMix:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.ArrozLecheEvolved:2;SapphCooking.ShavedIceEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2;SapphCooking.FriedRiceWok:2")
	end

    local item = ScriptManager.instance:getItem("SapphCooking.PipingBag_Icing")
	if item then
		item:getTags():add("Icing")
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.BlenderShake:10;SapphCooking.BlenderSmoothie:10;SapphCooking.FrenchToastEvolved:10;SapphCooking.CrepesEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.WhippedCream_Can")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.BlenderShake:5;SapphCooking.BlenderSmoothie:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.CrepesEvolved:5")
	end

    local item = ScriptManager.instance:getItem("SapphCooking.PipingBag_PastryCream")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.BlenderShake:10;SapphCooking.BlenderSmoothie:10;SapphCooking.FrenchToastEvolved:10;SapphCooking.CrepesEvolved:10")
	end

    local item = ScriptManager.instance:getItem("SapphCooking.Saucepan_Custard_Cooked")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.BlenderShake:10;SapphCooking.BlenderSmoothie:10;SapphCooking.FrenchToastEvolved:10;SapphCooking.CrepesEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Bonbon")
	if item then
		item:getTags():add("Chocolate")
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:4;SapphCooking.MacaronRed:4;SapphCooking.MacaronBlue:4;SapphCooking.MacaronGreen:4;SapphCooking.MacaronYellow:4;SapphCooking.MacaronPurple:4;SapphCooking.Cake_Chocolate:5;SapphCooking.Cake_Carrot:5;SapphCooking.Cake_BlackForest:5;SapphCooking.Cake_RedVelvet:5;SapphCooking.Cake_Strawberry:5;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Bonbon_Liqueur")
	if item then
		item:getTags():add("Chocolate")
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:4;SapphCooking.MacaronRed:4;SapphCooking.MacaronBlue:4;SapphCooking.MacaronGreen:4;SapphCooking.MacaronYellow:4;SapphCooking.MacaronPurple:4;SapphCooking.Cake_Chocolate:5;SapphCooking.Cake_Carrot:5;SapphCooking.Cake_BlackForest:5;SapphCooking.Cake_RedVelvet:5;SapphCooking.Cake_Strawberry:5;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Heart_Chocolate")
	if item then
		item:getTags():add("Chocolate")
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:4;SapphCooking.MacaronRed:4;SapphCooking.MacaronBlue:4;SapphCooking.MacaronGreen:4;SapphCooking.MacaronYellow:4;SapphCooking.MacaronPurple:4;SapphCooking.Cake_Chocolate:5;SapphCooking.Cake_Carrot:5;SapphCooking.Cake_BlackForest:5;SapphCooking.Cake_RedVelvet:5;SapphCooking.Cake_Strawberry:5;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.ChocolateEgg_Small")
	if item then
		item:getTags():add("Chocolate")
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:4;SapphCooking.MacaronRed:4;SapphCooking.MacaronBlue:4;SapphCooking.MacaronGreen:4;SapphCooking.MacaronYellow:4;SapphCooking.MacaronPurple:4;SapphCooking.Cake_Chocolate:5;SapphCooking.Cake_Carrot:5;SapphCooking.Cake_BlackForest:5;SapphCooking.Cake_RedVelvet:5;SapphCooking.Cake_Strawberry:5;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.ChocolateEgg_Medium")
	if item then
		item:getTags():add("Chocolate")
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:4;SapphCooking.MacaronRed:4;SapphCooking.MacaronBlue:4;SapphCooking.MacaronGreen:4;SapphCooking.MacaronYellow:4;SapphCooking.MacaronPurple:4;SapphCooking.Cake_Chocolate:5;SapphCooking.Cake_Carrot:5;SapphCooking.Cake_BlackForest:5;SapphCooking.Cake_RedVelvet:5;SapphCooking.Cake_Strawberry:5;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.ChocolateEgg_Large")
	if item then
		item:getTags():add("Chocolate")
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:4;SapphCooking.MacaronRed:4;SapphCooking.MacaronBlue:4;SapphCooking.MacaronGreen:4;SapphCooking.MacaronYellow:4;SapphCooking.MacaronPurple:4;SapphCooking.Cake_Chocolate:5;SapphCooking.Cake_Carrot:5;SapphCooking.Cake_BlackForest:5;SapphCooking.Cake_RedVelvet:5;SapphCooking.Cake_Strawberry:5;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2")
	end
	

	
    










    --vanila

	--this is for making birthday cakes~
	local item = ScriptManager.instance:getItem("Base.CakeRaw")
	if item then
		item:getTags():add("isCake")
	end

    local item = ScriptManager.instance:getItem("Base.Sugar")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.BowlSorbet:2;SapphCooking.FrenchToastEvolved:2;SapphCooking.BlenderShake:1;SapphCooking.CocktailMix:1;SapphCooking.SpringrollEvolved:1;SapphCooking.ArrozLecheEvolved:1;SapphCooking.ShavedIceEvolved:1;SapphCooking.CoffeeThermosEvolved:1;HotDrink:1;HotDrinkRed:1;HotDrinkWhite:1;HotDrinkSpiffo:1;HotDrinkTea:1;Toast:1;Oatmeal:1;Beverage:1;Beverage2:1;SapphCooking.ThermosBeverage:1")
	end

	local item = ScriptManager.instance:getItem("Base.SugarBrown")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.BowlSorbet:2;SapphCooking.FrenchToastEvolved:2;SapphCooking.BlenderShake:1;SapphCooking.CocktailMix:1;SapphCooking.SpaguettiEvolved:1;SapphCooking.SpringrollEvolved:1;SapphCooking.ArrozLecheEvolved:1;SapphCooking.ShavedIceEvolved:1;SapphCooking.CoffeeThermosEvolved:1;HotDrink:1;HotDrinkRed:1;HotDrinkWhite:1;HotDrinkSpiffo:1;HotDrinkTea:1;Toast:1;Oatmeal:1;Beverage:1;Beverage2:1;SapphCooking.ThermosBeverage:1")
	end

	local item = ScriptManager.instance:getItem("Base.SugarPacket")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:1;SapphCooking.BowlSorbet:1;SapphCooking.FrenchToastEvolved:1;SapphCooking.BlenderShake:1;SapphCooking.CocktailMix:1;SapphCooking.SpaguettiEvolved:1;SapphCooking.SpringrollEvolved:1;SapphCooking.ArrozLecheEvolved:1;SapphCooking.ShavedIceEvolved:1;HotDrink:1;HotDrinkRed:1;HotDrinkWhite:1;HotDrinkSpiffo:1;HotDrinkTea:1;Toast:1;Oatmeal:1;Beverage:1;Beverage2:1;SapphCooking.ThermosBeverage:1")
	end

	local item = ScriptManager.instance:getItem("Base.CocoaPowder")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.BowlSorbet:2;SapphCooking.FrenchToastEvolved:2;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.SpringrollEvolved:4;SapphCooking.ArrozLecheEvolved:4;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:5;HotDrink:5;HotDrinkRed:5;HotDrinkWhite:5;HotDrinkSpiffo:5;HotDrinkTea:5;ConeIcecream:5;Pancakes:5;Waffles:5;SapphCooking.ThermosBeverage:5")
	end

    local item = ScriptManager.instance:getItem("Base.Chocolate")
	if item then
		item:getTags():add("Chocolate")
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:4;SapphCooking.MacaronRed:4;SapphCooking.MacaronBlue:4;SapphCooking.MacaronGreen:4;SapphCooking.MacaronYellow:4;SapphCooking.MacaronPurple:4;SapphCooking.Cake_Chocolate:5;SapphCooking.Cake_Carrot:5;SapphCooking.Cake_BlackForest:5;SapphCooking.Cake_RedVelvet:5;SapphCooking.Cake_Strawberry:5;SapphCooking.ChurrosEvolved:2;SapphCooking.ChurrosChocolateEvolved:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2")
	end

	local item = ScriptManager.instance:getItem("Base.Icing")
	if item then
		item:getTags():add("Icing")
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.BlenderShake:10;SapphCooking.BlenderSmoothie:10;SapphCooking.FrenchToastEvolved:10;SapphCooking.CrepesEvolved:10")
	end

	local item = ScriptManager.instance:getItem("Base.GrahamCrackers")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.Crackers")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.Cereal")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.Pretzel")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

    local item = ScriptManager.instance:getItem("Base.Allsorts")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.LicoriceBlack")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.LicoriceRed")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end


	local item = ScriptManager.instance:getItem("Base.CandyFruitSlices")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.CandyCorn")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.Candycane")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end
	
	local item = ScriptManager.instance:getItem("Base.ChocolateChips")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.GummyWorms")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.HardCandies")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.HiHis")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.Icecream")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.Jellybeans")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.Jujubes")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.Marshmallows")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.SnoGlobes")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.Modjeska")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end

	local item = ScriptManager.instance:getItem("Base.Snackcakes_Plonkies")
	if item then
		item:DoParam("EvolvedRecipe =  SapphCooking.Cake_Chocolate:2;SapphCooking.Cake_Carrot:2;SapphCooking.Cake_BlackForest:2;SapphCooking.Cake_RedVelvet:2;SapphCooking.Cake_Strawberry:2;SapphCooking.BagelPlainEvolved:2;SapphCooking.EclairEvolved:2;SapphCooking.EclairChocolateEvolved:2;SapphCooking.EclairWhiteChocolateEvolved:2;SapphCooking.DoughnutsEvolved:2;SapphCooking.DoughnutsChocolateEvolved:2;SapphCooking.LasagnaEvolved:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.FrenchToastEvolved:5;SapphCooking.BowlSorbet:5;SapphCooking.BlenderShake:5;SapphCooking.CocktailMix:5;SapphCooking.SpringrollEvolved:5;SapphCooking.ArrozLecheEvolved:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;Beverage:2;Beverage2:2;Cake:5;Sandwich:2;Sandwich Baguette:2;FruitSalad:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Pancakes:2;Waffles:2;ConeIcecream:2;PieSweet:5;Toast:2;Oatmeal:2")
	end


end
CustomCandyTweakRecipes()
Events.OnInitGlobalModData.Add(CustomCandyTweakRecipes)