-- custom evolved item tweaks will be here!
-- this means anything with the modID: "SapphCooking"!


local function CustomTweakRecipes()


	local item = ScriptManager.instance:getItem("SapphCooking.NoodleSachet_Beef")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.CornCob:4;SapphCooking.SpaguettiEvolved:4;SapphCooking.InstantNoodles:4;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:1;SapphCooking.YakisobaEvolved:1;SapphCooking.RatatouilleEvolved:1;SapphCooking.LasagnaEvolved:1;SapphCooking.SkewersInsect:1;SapphCooking.SkewersMeat:1;SapphCooking.SkewersVegetable:1;SapphCooking.SapphCrackers:1;SapphCooking.SapphCrackers2:1;SapphCooking.FriedRiceWok:1;SapphCooking.BakedPotatoEvolved:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.NoodleSachet_Chicken")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.CornCob:4;SapphCooking.SpaguettiEvolved:4;SapphCooking.InstantNoodles:4;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:1;SapphCooking.YakisobaEvolved:1;SapphCooking.RatatouilleEvolved:1;SapphCooking.LasagnaEvolved:1;SapphCooking.SkewersInsect:1;SapphCooking.SkewersMeat:1;SapphCooking.SkewersVegetable:1;SapphCooking.SapphCrackers:1;SapphCooking.SapphCrackers2:1;SapphCooking.FriedRiceWok:1;SapphCooking.BakedPotatoEvolved:2")
	end


	--Pans
	local item = ScriptManager.instance:getItem("SapphCooking.SaucepanwithArborioRice")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LettuceWrapEvolved:5;SapphCooking.FlatbreadEvolved:8;SapphCooking.BorschtEvolved:5;SapphCooking.InstantNoodles:5;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:10;SapphCooking.HotdogSandwich:10;Taco:10;Burrito:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SaucepanwithBrownRice")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LettuceWrapEvolved:5;SapphCooking.FlatbreadEvolved:8;SapphCooking.BorschtEvolved:5;SapphCooking.InstantNoodles:5;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;Taco:10;Burrito:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SaucepanwithSpaguetti")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LettuceWrapEvolved:5;SapphCooking.FlatbreadEvolved:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.HotdogEvolved:8;Taco:9;Burrito:18")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SaucepanwithSpaguettiandMeatballs")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LettuceWrapEvolved:5;SapphCooking.FlatbreadEvolved:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.HotdogEvolved:8;Taco:9;Burrito:18")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SaucepanwithBeefStew")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.FlatbreadEvolved:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:9;Taco:9;Burrito:18")
	end

			--Bowls

	local item = ScriptManager.instance:getItem("SapphCooking.BowlofChickenStroganoff")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LettuceWrapEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.InstantNoodles:4;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:9;SapphCooking.HotdogSandwich:9;Taco:9;Burrito:18")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BowlofYakisoba")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LettuceWrapEvolved:5;SapphCooking.FlatbreadEvolved:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:10;SapphCooking.HotdogSandwich:10;Taco:10;Burrito:15")
	end

	


	local item = ScriptManager.instance:getItem("SapphCooking.ArborioRiceBowl")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LettuceWrapEvolved:5;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;Pizza:10;Burger:10;Omelette:10;Stir fry Griddle Pan:10;Stir fry:10;Stew:10;Pie:10;Soup:10;Sandwich:10;Sandwich Baguette:10;Salad:10;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BrownRiceBowl")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LettuceWrapEvolved:5;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;Pizza:10;Burger:10;Omelette:10;Stir fry Griddle Pan:10;Stir fry:10;Stew:10;Pie:10;Soup:10;Sandwich:10;Sandwich Baguette:10;Salad:10;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BowlofBeefStew")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;SapphCooking.SkewersInsect:8;SapphCooking.SkewersVegetable:8;SapphCooking.SkewersMeat:8;Pizza:10;Burger:10;Omelette:10;Stir fry Griddle Pan:10;Stir fry:10;Stew:10;Pie:10;Soup:10;Sandwich:10;Sandwich Baguette:10;Salad:10;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BowlofGuacamole")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CornCob:6;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;SapphCooking.SkewersInsect:8;SapphCooking.SkewersVegetable:8;SapphCooking.SkewersMeat:8;Pizza:10;Burger:10;Omelette:10;Stir fry Griddle Pan:10;Stir fry:10;Stew:10;Pie:10;Soup:10;Sandwich:10;Sandwich Baguette:10;Salad:10;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BowlofQueso")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CornCob:6;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;SapphCooking.SkewersInsect:8;SapphCooking.SkewersVegetable:8;SapphCooking.SkewersMeat:8;Pizza:10;Burger:10;Omelette:10;Stir fry Griddle Pan:10;Stir fry:10;Stew:10;Pie:10;Soup:10;Sandwich:10;Sandwich Baguette:10;Salad:10;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Bowl_Puree")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;SapphCooking.SkewersInsect:8;SapphCooking.SkewersVegetable:8;SapphCooking.SkewersMeat:8;Pizza:10;Burger:10;Omelette:10;Stir fry Griddle Pan:10;Stir fry:10;Stew:10;Pie:10;Soup:10;Sandwich:10;Sandwich Baguette:10;Salad:10;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end


	local item = ScriptManager.instance:getItem("SapphCooking.BowlofRefriedBeans")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;SapphCooking.SkewersInsect:8;SapphCooking.SkewersVegetable:8;SapphCooking.SkewersMeat:8;Pizza:10;Burger:10;Omelette:10;Stir fry Griddle Pan:10;Stir fry:10;Stew:10;Pie:10;Soup:10;Sandwich:10;Sandwich Baguette:10;Salad:10;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BowlofSpaguetti")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;SapphCooking.SkewersInsect:8;SapphCooking.SkewersVegetable:8;SapphCooking.SkewersMeat:8;Pizza:10;Burger:10;Omelette:10;Stir fry Griddle Pan:10;Stir fry:10;Stew:10;Pie:10;Soup:10;Sandwich:10;Sandwich Baguette:10;Salad:10;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BowlofSpaguettiandMeatballs")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LettuceWrapEvolved:5;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;SapphCooking.SkewersInsect:8;SapphCooking.SkewersVegetable:8;SapphCooking.SkewersMeat:8;Pizza:10;Burger:10;Omelette:10;Stir fry Griddle Pan:10;Stir fry:10;Stew:10;Pie:10;Soup:10;Sandwich:10;Sandwich Baguette:10;Salad:10;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BowlofChili")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CornCob:6;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;SapphCooking.SkewersInsect:8;SapphCooking.SkewersVegetable:8;SapphCooking.SkewersMeat:8;Pizza:10;Burger:10;Omelette:10;Stir fry Griddle Pan:10;Stir fry:10;Stew:10;Pie:10;Soup:10;Sandwich:10;Sandwich Baguette:10;Salad:10;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.RiceBeanBowl")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LettuceWrapEvolved:5;SapphCooking.CornCob:6;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;SapphCooking.SkewersInsect:8;SapphCooking.SkewersVegetable:8;SapphCooking.SkewersMeat:8;Pizza:10;Burger:10;Omelette:10;Stir fry Griddle Pan:10;Stir fry:10;Stew:10;Pie:10;Soup:10;Sandwich:10;Sandwich Baguette:10;Salad:10;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end


	--Egg
	
	local item = ScriptManager.instance:getItem("SapphCooking.BrownEgg")
	if item then---
		item:DoParam("EvolvedRecipe	= SapphCooking.StuffedPepperEvolved:7;SapphCooking.FlatbreadEvolved:7;SapphCooking.WokRoastVeg:7;SapphCooking.BlenderShake:7;SapphCooking.BorschtEvolved:7;SapphCooking.HR1:7;SapphCooking.HR2:7;SapphCooking.HR3:7;SapphCooking.HR4:7;SapphCooking.SpaguettiEvolved:7;SapphCooking.InstantNoodles:7;SapphCooking.FryingPanwithFriedRice:7;SapphCooking.SpringrollEvolved:7;SapphCooking.PoutineEvolved:7;SapphCooking.YakisobaEvolved:10;SapphCooking.BakedPotatoEvolved:10;SapphCooking.LasagnaEvolved:10;SapphCooking.RatatouilleEvolved:7;SapphCooking.FriedRiceWok:10;Stir fry Griddle Pan:10;Stir fry:10;Sandwich:10|Cooked;Sandwich Baguette:10|Cooked;Burger:10;Salad:10|Cooked;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Cured_EggYolk")
	if item then---
		item:DoParam("EvolvedRecipe	= SapphCooking.FlatbreadEvolved:7;SapphCooking.WokRoastVeg:7;SapphCooking.BlenderShake:7;SapphCooking.BorschtEvolved:7;SapphCooking.HR1:7;SapphCooking.HR2:7;SapphCooking.HR3:7;SapphCooking.HR4:7;SapphCooking.SpaguettiEvolved:7;SapphCooking.InstantNoodles:7;SapphCooking.FryingPanwithFriedRice:7;SapphCooking.SpringrollEvolved:7;SapphCooking.PoutineEvolved:7;SapphCooking.YakisobaEvolved:10;SapphCooking.BakedPotatoEvolved:10;SapphCooking.LasagnaEvolved:10;SapphCooking.RatatouilleEvolved:7;SapphCooking.FriedRiceWok:10;Stir fry Griddle Pan:10;Stir fry:10;Sandwich:10|Cooked;Sandwich Baguette:10|Cooked;Burger:10;Salad:10|Cooked;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end

	--Thermos

	

	local item = ScriptManager.instance:getItem("SapphCooking.BottleofLemonJuice")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.CocktailMix:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2;SapphCooking.BakedPotatoEvolved:2;SapphCooking.FriedRiceWok:2;SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.CocktailMix:5;SapphCooking.CoffeeThermosEvolved:5;HotDrink:5;HotDrinkRed:5;HotDrinkWhite:5;HotDrinkSpiffo:5;HotDrinkTea:5;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BottleofGrapeJuice")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.CocktailMix:5;SapphCooking.CoffeeThermosEvolved:5;HotDrink:5;HotDrinkRed:5;HotDrinkWhite:5;HotDrinkSpiffo:5;HotDrinkTea:5;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BottleofAppleJuice")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.CocktailMix:5;SapphCooking.CoffeeThermosEvolved:5;HotDrink:5;HotDrinkRed:5;HotDrinkWhite:5;HotDrinkSpiffo:5;HotDrinkTea:5;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BottleofStrawberryJuice")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.CocktailMix:5;SapphCooking.CoffeeThermosEvolved:5;HotDrink:5;HotDrinkRed:5;HotDrinkWhite:5;HotDrinkSpiffo:5;HotDrinkTea:5;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BottleofOrangeJuice")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.CocktailMix:5;SapphCooking.CoffeeThermosEvolved:5;HotDrink:5;HotDrinkRed:5;HotDrinkWhite:5;HotDrinkSpiffo:5;HotDrinkTea:5;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BottleofPeachJuice")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.CocktailMix:5;SapphCooking.CoffeeThermosEvolved:5;HotDrink:5;HotDrinkRed:5;HotDrinkWhite:5;HotDrinkSpiffo:5;HotDrinkTea:5;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BottleofWatermelonJuice")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:5;SapphCooking.ShavedIceEvolved:5;SapphCooking.CocktailMix:5;SapphCooking.CoffeeThermosEvolved:5;HotDrink:5;HotDrinkRed:5;HotDrinkWhite:5;HotDrinkSpiffo:5;HotDrinkTea:5;SapphCooking.ThermosBeverage:5")
	end


	local item = ScriptManager.instance:getItem("SapphCooking.IceCubes")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:1;SapphCooking.CocktailCupEvolved:1;SapphCooking.BlenderShake:1;SapphCooking.CocktailMix:1;SapphCooking.CoffeeThermosEvolved:1;HotDrink:1;HotDrinkRed:1;HotDrinkWhite:1;HotDrinkSpiffo:1;HotDrinkTea:1;SapphCooking.ThermosBeverage:1")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.CoffeePacket")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.MacaronPink:2;SapphCooking.MacaronRed:2;SapphCooking.MacaronBlue:2;SapphCooking.MacaronGreen:2;SapphCooking.MacaronYellow:2;SapphCooking.MacaronPurple:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.BlenderShake:1;SapphCooking.CocktailMix:1;SapphCooking.ShavedIceEvolved:1;SapphCooking.CoffeeThermosEvolved:1;HotDrink:1;HotDrinkRed:1;HotDrinkWhite:1;HotDrinkSpiffo:1;HotDrinkTea:1;Toast:1;Oatmeal:1;Beverage:1;Beverage2:1;SapphCooking.ThermosBeverage:1")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SaucepanHotChocolate")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:10;HotDrink:10;HotDrinkRed:10;HotDrinkWhite:10;HotDrinkSpiffo:10;HotDrinkTea:10;SapphCooking.ThermosBeverage:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.AlmondMilk")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.SpaguettiEvolved:2;SapphCooking.ArrozLecheEvolved:2;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:4;FruitSalad:2;Pancakes:2;Waffles:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Beverage:5;Beverage2:5;Oatmeal:2;PieSweet:5;Cake:5;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BottlewithMilk")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.SpaguettiEvolved:2;SapphCooking.ArrozLecheEvolved:2;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:4;FruitSalad:2;Pancakes:2;Waffles:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Beverage:5;Beverage2:5;Oatmeal:2;PieSweet:5;Cake:5;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.PopbottlewithMilk")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.SpaguettiEvolved:2;SapphCooking.ArrozLecheEvolved:2;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:4;FruitSalad:2;Pancakes:2;Waffles:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Beverage:5;Beverage2:5;Oatmeal:2;PieSweet:5;Cake:5;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.ColaBottlewithMilk")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.SpaguettiEvolved:2;SapphCooking.ArrozLecheEvolved:2;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:4;FruitSalad:2;Pancakes:2;Waffles:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Beverage:5;Beverage2:5;Oatmeal:2;PieSweet:5;Cake:5;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.ColaBottlewithProteinShake")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:4;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BleachBottlewithProteinShake")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:4;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.PopBottlewithProteinShake")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:4;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.BottlewithProteinShake")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:4;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.StrawberryMilk")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.ArrozLecheEvolved:2;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:4;FruitSalad:2;Pancakes:2;Waffles:2;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Beverage:5;Beverage2:5;Oatmeal:2;PieSweet:5;Cake:5;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.TequilaFull")
	if item then
	item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.SpaguettiEvolved:2;SapphCooking.FryingPanwithFriedRice:4;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:5;Soup:8;Stew:8;Beer:9;Beer2:9;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.VodkaFull")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BowlSorbet:4;SapphCooking.BlenderShake:4;SapphCooking.BorschtEvolved:2;SapphCooking.CocktailMix:4;SapphCooking.SpaguettiEvolved:2;SapphCooking.FryingPanwithFriedRice:4;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:5;Soup:8;Stew:8;Beer:9;Beer2:9;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.CachacaFull")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BowlSorbet:4;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.SpaguettiEvolved:2;SapphCooking.FryingPanwithFriedRice:4;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:5;Soup:8;Stew:8;Beer:9;Beer2:9;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.GinFull")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BowlSorbet:4;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.SpaguettiEvolved:2;SapphCooking.FryingPanwithFriedRice:4;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:5;Soup:8;Stew:8;Beer:9;Beer2:9;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SakeFull")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BowlSorbet:4;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.SpaguettiEvolved:2;SapphCooking.FryingPanwithFriedRice:4;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:5;Soup:8;Stew:8;Beer:9;Beer2:9;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.RumFull")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BowlSorbet:4;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.SpaguettiEvolved:2;SapphCooking.FryingPanwithFriedRice:4;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:5;Soup:8;Stew:8;Beer:9;Beer2:9;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.ColaBottle")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BowlSorbet:4;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.ShavedIceEvolved:5;SapphCooking.CoffeeThermosEvolved:5;SapphCooking.ThermosBeverage:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.EnergyDrink")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.LowballCupEvolved:4;SapphCooking.CocktailCupEvolved:4;SapphCooking.BowlSorbet:4;SapphCooking.BlenderShake:4;SapphCooking.CocktailMix:4;SapphCooking.ArrozLecheEvolved:2;SapphCooking.ShavedIceEvolved:4;SapphCooking.CoffeeThermosEvolved:5;HotDrink:2;HotDrinkRed:2;HotDrinkWhite:2;HotDrinkSpiffo:2;HotDrinkTea:2;Beverage:2;Beverage2:2;Oatmeal:2;SapphCooking.ThermosBeverage:4")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.PotatoPeel")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StockEvolved:1;Stew:1;Soup:1")
	end


--MEAT

	local item = ScriptManager.instance:getItem("SapphCooking.MincedMeat_Chicken")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5|Cooked;SapphCooking.CrepesEvolved:10|Cooked;SapphCooking.FlatbreadEvolved:15;SapphCooking.WokRoastVeg:15;SapphCooking.BorschtEvolved:15|Cooked;SapphCooking.HR1:15|Cooked;SapphCooking.HR2:15|Cooked;SapphCooking.HR3:15|Cooked;SapphCooking.HR4:15|Cooked;SapphCooking.SpaguettiEvolved:15;SapphCooking.InstantNoodles:15;SapphCooking.FryingPanwithFriedRice:15;SapphCooking.SpringrollEvolved:15;SapphCooking.PoutineEvolved:15;SapphCooking.SausageEvolved:15;SapphCooking.DumplingsEvolved:15;SapphCooking.HotdogSandwich:15|Cooked;SapphCooking.HotdogEvolved:15|Cooked;SapphCooking.SushiEvolved:15;SapphCooking.YakisobaEvolved:15;SapphCooking.LasagnaEvolved:15;Pizza:20;Stew:20;Pie:20;Sandwich:5|Cooked;Sandwich Baguette:5|Cooked;Burger:10|Cooked;Taco:10|Cooked;Burrito:10|Cooked;SapphCooking.SkewersMeat:10;SapphCooking.FriedRiceWok:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SausageEvolved")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5|Cooked;SapphCooking.CrepesEvolved:10|Cooked;SapphCooking.FlatbreadEvolved:10;SapphCooking.WokRoastVeg:10;SapphCooking.BorschtEvolved:10|Cooked;SapphCooking.HR1:10|Cooked;SapphCooking.HR2:10|Cooked;SapphCooking.HR3:10|Cooked;SapphCooking.HR4:10|Cooked;SapphCooking.SpaguettiEvolved:10;SapphCooking.InstantNoodles:10;SapphCooking.FryingPanwithFriedRice:10;SapphCooking.SpringrollEvolved:10;SapphCooking.PoutineEvolved:15;SapphCooking.DumplingsEvolved:15;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:15|Cooked;SapphCooking.HotdogEvolved:15|Cooked;SapphCooking.SushiEvolved:5;SapphCooking.YakisobaEvolved:15;SapphCooking.LasagnaEvolved:20;Pizza:20;Stew:20;Stir fry Griddle Pan:20;Stir fry:20;Burger:20|Cooked;Roasted Vegetables:20;PastaPot:20;PastaPan:20;RicePot:20;RicePan:20;Taco:5|Cooked;Burrito:10|Cooked;SapphCooking.SkewersMeat:10;SapphCooking.FriedRiceWok:10;SapphCooking.BakedPotatoEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SlicedSteak")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5|Cooked;SapphCooking.CrepesEvolved:10|Cooked;SapphCooking.FlatbreadEvolved:10;SapphCooking.WokRoastVeg:10;SapphCooking.BorschtEvolved:10|Cooked;SapphCooking.HR1:10|Cooked;SapphCooking.HR2:10|Cooked;SapphCooking.HR3:10|Cooked;SapphCooking.HR4:10|Cooked;SapphCooking.SpaguettiEvolved:10;SapphCooking.InstantNoodles:10;SapphCooking.FryingPanwithFriedRice:10;SapphCooking.SpringrollEvolved:10;SapphCooking.PoutineEvolved:15;SapphCooking.DumplingsEvolved:15;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:15|Cooked;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:10;SapphCooking.LasagnaEvolved:10;SapphCooking.SkewersMeat:10;Pizza:15;Stew:15;Stir fry Griddle Pan:15;Stir fry:15;Sandwich:5|Cooked;Sandwich Baguette:5|Cooked;Salad:10|Cooked;Roasted Vegetables:15;PastaPot:15;PastaPan:15;RicePot:15;RicePan:15;Taco:15|Cooked;Burrito:15|Cooked;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SlicedChicken")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5|Cooked;SapphCooking.CrepesEvolved:10|Cooked;SapphCooking.FlatbreadEvolved:10;SapphCooking.WokRoastVeg:10;SapphCooking.BorschtEvolved:10|Cooked;SapphCooking.HR1:10|Cooked;SapphCooking.HR2:10|Cooked;SapphCooking.HR3:10|Cooked;SapphCooking.HR4:10|Cooked;SapphCooking.SpaguettiEvolved:10;SapphCooking.InstantNoodles:10;SapphCooking.FryingPanwithFriedRice:10;SapphCooking.SpringrollEvolved:10;SapphCooking.PoutineEvolved:15;SapphCooking.DumplingsEvolved:15;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:10|Cooked;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:10;SapphCooking.LasagnaEvolved:10;SapphCooking.SkewersMeat:10;Pizza:12;Soup:15;Stew:15;Pie:12;Stir fry Griddle Pan:15;Stir fry:15;Sandwich:6|Cooked;Sandwich Baguette:6|Cooked;Burger:12|Cooked;Salad:6|Cooked;Roasted Vegetables:15;RicePot:15;RicePan:15;PastaPot:15;PastaPan:15;Taco:6|Cooked;Burrito:12|Cooked;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.TenderizedMeat")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5|Cooked;SapphCooking.CrepesEvolved:10|Cooked;SapphCooking.FlatbreadEvolved:10;SapphCooking.WokRoastVeg:10;SapphCooking.BorschtEvolved:10|Cooked;SapphCooking.HR1:10|Cooked;SapphCooking.HR2:10|Cooked;SapphCooking.HR3:10|Cooked;SapphCooking.HR4:10|Cooked;SapphCooking.SpaguettiEvolved:10;SapphCooking.InstantNoodles:10;SapphCooking.FryingPanwithFriedRice:10;SapphCooking.SpringrollEvolved:10;SapphCooking.PoutineEvolved:15;SapphCooking.DumplingsEvolved:15;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:10|Cooked;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:10;SapphCooking.LasagnaEvolved:10;SapphCooking.SkewersMeat:10;Pizza:12;Soup:15;Stew:15;Pie:12;Stir fry Griddle Pan:15;Stir fry:15;Sandwich:6|Cooked;Sandwich Baguette:6|Cooked;Burger:12|Cooked;Salad:6|Cooked;Roasted Vegetables:15;RicePot:15;RicePan:15;PastaPot:15;PastaPan:15;Taco:6|Cooked;Burrito:12|Cooked;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Meatballs")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5|Cooked;SapphCooking.CrepesEvolved:10|Cooked;SapphCooking.FlatbreadEvolved:10|Cooked;SapphCooking.WokRoastVeg:10|Cooked;SapphCooking.BorschtEvolved:10|Cooked;SapphCooking.HR1:10|Cooked;SapphCooking.HR2:10|Cooked;SapphCooking.HR3:10|Cooked;SapphCooking.HR4:10|Cooked;SapphCooking.SpaguettiEvolved:10|Cooked;SapphCooking.InstantNoodles:10|Cooked;SapphCooking.FryingPanwithFriedRice:10|Cooked;SapphCooking.SpringrollEvolved:10|Cooked;SapphCooking.PoutineEvolved:15|Cooked;SapphCooking.DumplingsEvolved:15|Cooked;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:10|Cooked;SapphCooking.SushiEvolved:8|Cooked;SapphCooking.YakisobaEvolved:10;SapphCooking.LasagnaEvolved:10;SapphCooking.SkewersMeat:10;Pizza:12;Soup:15;Stew:15;Pie:12;Stir fry Griddle Pan:15;Stir fry:15;Sandwich:6|Cooked;Sandwich Baguette:6|Cooked;Burger:12|Cooked;Salad:6|Cooked;Roasted Vegetables:15;RicePot:15;RicePan:15;PastaPot:15;PastaPan:15;Taco:6|Cooked;Burrito:12|Cooked;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SmashBurger")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5|Cooked;SapphCooking.CrepesEvolved:10|Cooked;SapphCooking.FlatbreadEvolved:10|Cooked;SapphCooking.WokRoastVeg:10|Cooked;SapphCooking.BorschtEvolved:10|Cooked;SapphCooking.HR1:10|Cooked;SapphCooking.HR2:10|Cooked;SapphCooking.HR3:10|Cooked;SapphCooking.HR4:10|Cooked;SapphCooking.SpaguettiEvolved:10|Cooked;SapphCooking.InstantNoodles:10|Cooked;SapphCooking.FryingPanwithFriedRice:10|Cooked;SapphCooking.SpringrollEvolved:10|Cooked;SapphCooking.PoutineEvolved:15|Cooked;SapphCooking.DumplingsEvolved:15|Cooked;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:10|Cooked;SapphCooking.SushiEvolved:8|Cooked;SapphCooking.YakisobaEvolved:10;SapphCooking.LasagnaEvolved:10;SapphCooking.SkewersMeat:10;Pizza:12;Soup:15;Stew:15;Pie:12;Stir fry Griddle Pan:15;Stir fry:15;Sandwich:6|Cooked;Sandwich Baguette:6|Cooked;Burger:12|Cooked;Salad:6|Cooked;Roasted Vegetables:15;RicePot:15;RicePan:15;PastaPot:15;PastaPan:15;Taco:6|Cooked;Burrito:12|Cooked;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.FriedRat")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5|Cooked;SapphCooking.CrepesEvolved:10|Cooked;SapphCooking.FlatbreadEvolved:10|Cooked;SapphCooking.WokRoastVeg:10|Cooked;SapphCooking.BorschtEvolved:10|Cooked;SapphCooking.HR1:10|Cooked;SapphCooking.HR2:10|Cooked;SapphCooking.HR3:10|Cooked;SapphCooking.HR4:10|Cooked;SapphCooking.SpaguettiEvolved:10|Cooked;SapphCooking.InstantNoodles:10|Cooked;SapphCooking.FryingPanwithFriedRice:10|Cooked;SapphCooking.SpringrollEvolved:10|Cooked;SapphCooking.PoutineEvolved:15|Cooked;SapphCooking.DumplingsEvolved:15|Cooked;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:10|Cooked;SapphCooking.SushiEvolved:8|Cooked;SapphCooking.YakisobaEvolved:10;SapphCooking.LasagnaEvolved:10;SapphCooking.SkewersMeat:10;Pizza:12;Soup:15;Stew:15;Pie:12;Stir fry Griddle Pan:15;Stir fry:15;Sandwich:6|Cooked;Sandwich Baguette:6|Cooked;Burger:12|Cooked;Salad:6|Cooked;Roasted Vegetables:15;RicePot:15;RicePan:15;PastaPot:15;PastaPan:15;Taco:6|Cooked;Burrito:12|Cooked;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Falafel_Fried")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5|Cooked;SapphCooking.CrepesEvolved:10|Cooked;SapphCooking.FlatbreadEvolved:10|Cooked;SapphCooking.WokRoastVeg:10|Cooked;SapphCooking.BorschtEvolved:10|Cooked;SapphCooking.HR1:10|Cooked;SapphCooking.HR2:10|Cooked;SapphCooking.HR3:10|Cooked;SapphCooking.HR4:10|Cooked;SapphCooking.SpaguettiEvolved:10|Cooked;SapphCooking.InstantNoodles:10|Cooked;SapphCooking.FryingPanwithFriedRice:10|Cooked;SapphCooking.SpringrollEvolved:10|Cooked;SapphCooking.PoutineEvolved:15|Cooked;SapphCooking.DumplingsEvolved:15|Cooked;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:10|Cooked;SapphCooking.SushiEvolved:8|Cooked;SapphCooking.YakisobaEvolved:10;SapphCooking.LasagnaEvolved:10;SapphCooking.SkewersMeat:10;Pizza:12;Soup:15;Stew:15;Pie:12;Stir fry Griddle Pan:15;Stir fry:15;Sandwich:6|Cooked;Sandwich Baguette:6|Cooked;Burger:12|Cooked;Salad:6|Cooked;Roasted Vegetables:15;RicePot:15;RicePan:15;PastaPot:15;PastaPan:15;Taco:6|Cooked;Burrito:12|Cooked;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end
	
	



	--VEGETABLES/Cheese

	local item = ScriptManager.instance:getItem("SapphCooking.DicedBroccoli")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;SapphCooking.SkewersInsect:8;SapphCooking.SkewersVegetable:8;SapphCooking.SkewersMeat:8;Pizza:10;Burger:10;Omelette:10;Stir fry Griddle Pan:10;Stir fry:10;Stew:10;Pie:10;Soup:10;Sandwich:10;Sandwich Baguette:10;Salad:10;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Seitan")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:5;SapphCooking.HR2:5;SapphCooking.HR3:5;SapphCooking.HR4:5;SapphCooking.SpaguettiEvolved:5;SapphCooking.InstantNoodles:10;SapphCooking.FryingPanwithFriedRice:10;SapphCooking.SpringrollEvolved:10;SapphCooking.PoutineEvolved:15;SapphCooking.DumplingsEvolved:15;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:10;SapphCooking.RatatouilleEvolved:10;SapphCooking.LasagnaEvolved:10;SapphCooking.SkewersInsect:8;SapphCooking.SkewersVegetable:10;SapphCooking.SkewersMeat:10;Pizza:12;Soup:15;Stew:15;Pie:12;Stir fry Griddle Pan:15;Stir fry:15;Sandwich:6|Cooked;Sandwich Baguette:6|Cooked;Burger:12|Cooked;Salad:6|Cooked;Roasted Vegetables:15;RicePot:15;RicePan:15;PastaPot:15;PastaPan:15;Taco:6|Cooked;Burrito:12|Cooked")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.ParmesanCheese")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CornCob:4;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.WokRoastVeg:5;SapphCooking.HR1:5;SapphCooking.HR2:5;SapphCooking.HR3:5;SapphCooking.HR4:5;SapphCooking.SpaguettiEvolved:5;SapphCooking.InstantNoodles:5;SapphCooking.FryingPanwithFriedRice:5;SapphCooking.SpringrollEvolved:5;SapphCooking.PoutineEvolved:5;SapphCooking.CevicheEvolved:5;SapphCooking.DumplingsEvolved:4;SapphCooking.HotdogSandwich:4;SapphCooking.HotdogEvolved:4;SapphCooking.SushiEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:5;SapphCooking.RatatouilleEvolved:5;SapphCooking.LasagnaEvolved:5;SapphCooking.SkewersVegetable:5;SapphCooking.SkewersMeat:5;SapphCooking.SkewersInsect:5;Pizza:15;Soup:10;Sandwich:5;Sandwich Baguette:5;Burger:5;Salad:5;PastaPot:10;PastaPan:10;Taco:5;Burrito:5;Bread:5;Toast:5;SapphCooking.BakedPotatoEvolved:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.CheeseSpray_Can")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CornCob:4;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.WokRoastVeg:5;SapphCooking.HR1:5;SapphCooking.HR2:5;SapphCooking.HR3:5;SapphCooking.HR4:5;SapphCooking.SpaguettiEvolved:5;SapphCooking.InstantNoodles:5;SapphCooking.FryingPanwithFriedRice:5;SapphCooking.SpringrollEvolved:5;SapphCooking.PoutineEvolved:5;SapphCooking.CevicheEvolved:5;SapphCooking.DumplingsEvolved:4;SapphCooking.HotdogSandwich:4;SapphCooking.HotdogEvolved:4;SapphCooking.SushiEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:5;SapphCooking.RatatouilleEvolved:5;SapphCooking.LasagnaEvolved:5;SapphCooking.SkewersVegetable:5;SapphCooking.SkewersMeat:5;SapphCooking.SkewersInsect:5;Pizza:15;Soup:10;Sandwich:5;Sandwich Baguette:5;Burger:5;Salad:5;PastaPot:10;PastaPan:10;Taco:5;Burrito:5;Bread:5;Toast:5;SapphCooking.BakedPotatoEvolved:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.MozzarelaCheese")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CornCob:4;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.WokRoastVeg:5;SapphCooking.HR1:5;SapphCooking.HR2:5;SapphCooking.HR3:5;SapphCooking.HR4:5;SapphCooking.SpaguettiEvolved:5;SapphCooking.InstantNoodles:5;SapphCooking.FryingPanwithFriedRice:5;SapphCooking.SpringrollEvolved:5;SapphCooking.PoutineEvolved:5;SapphCooking.CevicheEvolved:5;SapphCooking.DumplingsEvolved:4;SapphCooking.HotdogSandwich:4;SapphCooking.HotdogEvolved:4;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:5;SapphCooking.RatatouilleEvolved:5;SapphCooking.LasagnaEvolved:5;SapphCooking.SkewersVegetable:5;SapphCooking.SkewersMeat:5;SapphCooking.SkewersInsect:5;Pizza:15;Soup:10;Sandwich:5;Sandwich Baguette:5;Burger:5;Salad:5;PastaPot:10;PastaPan:10;Taco:5;Burrito:5;Bread:5;Toast:5;SapphCooking.BakedPotatoEvolved:5")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SlicedEggplant")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:5;SapphCooking.FryingPanwithFriedRice:5;SapphCooking.SpringrollEvolved:5;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:4;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;SapphCooking.SkewersVegetable:8;Pizza:8;Omelette:8;Soup:16;Stew:16;Pie:16;Stir fry Griddle Pan:16;Stir fry:16;Burger:8;Sandwich:4;Sandwich Baguette:4;Salad:8;Roasted Vegetables:16;RicePot:16;RicePan:16;PastaPot:16;PastaPan:16;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SlicedZucchini")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:5;SapphCooking.PoutineEvolved:10;SapphCooking.CevicheEvolved:10;SapphCooking.DumplingsEvolved:10;SapphCooking.StockEvolved:10;SapphCooking.HotdogSandwich:10;SapphCooking.HotdogEvolved:10;SapphCooking.SushiEvolved:10;SapphCooking.YakisobaEvolved:10;SapphCooking.RatatouilleEvolved:10;SapphCooking.LasagnaEvolved:10;SapphCooking.SkewersVegetable:10;Pizza:10;Soup:10;Stew:10;Pie:10;Stir fry Griddle Pan:10;Stir fry:10;Salad:10;Roasted Vegetables:10;RicePot:10;RicePan:10;PastaPot:10;PastaPan:10;Sandwich:5;Sandwich Baguette:5;Omelette:5;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SlicedTomato")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.BlenderPuree:8;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:12;SapphCooking.InstantNoodles:12;SapphCooking.FryingPanwithFriedRice:12;SapphCooking.SpringrollEvolved:12;SapphCooking.PoutineEvolved:12;SapphCooking.CevicheEvolved:12;SapphCooking.DumplingsEvolved:12;SapphCooking.StockEvolved:12;SapphCooking.HotdogSandwich:12;SapphCooking.HotdogEvolved:12;SapphCooking.SushiEvolved:12;SapphCooking.YakisobaEvolved:12;SapphCooking.RatatouilleEvolved:12;SapphCooking.LasagnaEvolved:12;SapphCooking.SkewersVegetable:4;Omelette:12;Soup:12;Stew:12;Pie:12;Stir fry Griddle Pan:12;Stir fry:12;Sandwich:6;Sandwich Baguette:6;Burger:6;Salad:12;Roasted Vegetables:12;RicePot:12;RicePan:12;PastaPot:12;PastaPan:12;Taco:12;Burrito:12;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SlicedCarrots")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.BlenderPuree:8;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;SapphCooking.SkewersVegetable:4;Soup:8;Stew:8;Pie:8;Stir fry Griddle Pan:8;Stir fry:8;Sandwich:8;Sandwich Baguette:8;Salad:8;Roasted Vegetables:8;RicePot:8;RicePan:8;PastaPot:8;PastaPan:8;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SlicedBellPepper")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;SapphCooking.SkewersVegetable:4;Omelette:8;Soup:8;Pie:8;Stir fry Griddle Pan:8;Stir fry:8;Sandwich:8;Sandwich Baguette:8;Burger:8;Salad:8;Roasted Vegetables:8;RicePot:8;RicePan:8;PastaPot:8;PastaPan:8;Taco:8;Burrito:8;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.PeeledPotato")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.BlenderPuree:8;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:15;SapphCooking.HotdogEvolved:15;SapphCooking.SushiEvolved:15;SapphCooking.YakisobaEvolved:15;SapphCooking.RatatouilleEvolved:15;SapphCooking.LasagnaEvolved:15;SapphCooking.SkewersVegetable:4;Omelette:8;Soup:8;Pie:8;Stir fry Griddle Pan:8;Stir fry:8;Sandwich:8;Sandwich Baguette:15;Burger:15;Salad:12;Roasted Vegetables:15;RicePot:15;RicePan:15;PastaPot:15;PastaPan:15;Taco:15;Burrito:15;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.CutPeeledPotato")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.BlenderPuree:8;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.SpaguettiEvolved:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.StockEvolved:8;SapphCooking.HotdogSandwich:15;SapphCooking.HotdogEvolved:15;SapphCooking.SushiEvolved:15;SapphCooking.YakisobaEvolved:15;SapphCooking.RatatouilleEvolved:15;SapphCooking.LasagnaEvolved:15;SapphCooking.SkewersVegetable:4;Omelette:8;Soup:8;Pie:8;Stir fry Griddle Pan:8;Stir fry:8;Sandwich:8;Sandwich Baguette:15;Burger:15;Salad:12;Roasted Vegetables:15;RicePot:15;RicePan:15;PastaPot:15;PastaPan:15;Taco:15;Burrito:15;SapphCooking.FriedRiceWok:15;SapphCooking.BakedPotatoEvolved:10")
	end


	--Spices

	local item = ScriptManager.instance:getItem("SapphCooking.TinofCaviar")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:2;SapphCooking.LettuceWrapEvolved:2;SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.CocktailMix:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2;SapphCooking.BakedPotatoEvolved:2;SapphCooking.FriedRiceWok:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SaltPacket")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:2;SapphCooking.LettuceWrapEvolved:2;SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.CocktailMix:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2;SapphCooking.BakedPotatoEvolved:2;SapphCooking.FriedRiceWok:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.HomemadeKetchup")
	if item then
		item:getTags():add("PizzaSauce")
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:5;SapphCooking.LettuceWrapEvolved:5;SapphCooking.CornCob:5;SapphCooking.CrepesEvolved:5;SapphCooking.FlatbreadEvolved:5;SapphCooking.WokRoastVeg:5;SapphCooking.HR1:5;SapphCooking.HR2:5;SapphCooking.HR3:5;SapphCooking.HR4:5;SapphCooking.CocktailMix:5;SapphCooking.InstantNoodles:5;SapphCooking.FryingPanwithFriedRice:5;SapphCooking.SpringrollEvolved:5;SapphCooking.PoutineEvolved:5;SapphCooking.CevicheEvolved:5;SapphCooking.SausageEvolved:5;SapphCooking.DumplingsEvolved:5;SapphCooking.HotdogSandwich:5;SapphCooking.HotdogEvolved:5;SapphCooking.SushiEvolved:5;SapphCooking.YakisobaEvolved:5;SapphCooking.RatatouilleEvolved:5;SapphCooking.LasagnaEvolved:5;Pizza:5;Omelette:5;Soup:5;Stew:5;Pie:5;Stir fry Griddle Pan:5;Stir fry:5;Burger:1;Salad:5;Roasted Vegetables:5;RicePot:5;RicePan:5;PastaPot:5;PastaPan:5;Sandwich:5;Sandwich Baguette:5;Taco:5;Burrito:5;SapphCooking.MRE_1:7;SapphCooking.MRE_2:7;SapphCooking.MRE_3:7;SapphCooking.MRE_4:7;SapphCooking.MRE_5:7;SapphCooking.MRE_6:7;SapphCooking.MRE_7:7;SapphCooking.MRE_8:7;SapphCooking.MRE_9:7;SapphCooking.MRE_10:7;SapphCooking.MRE_11:7;SapphCooking.MRE_12:7;SapphCooking.BowlofFriedRice:7;SapphCooking.BowlofOmurice:7;SapphCooking.ArborioRiceBowl:7;SapphCooking.BowlofRisotto:7;SapphCooking.BrownRiceBowl:7;SapphCooking.BowlofRavioli:7;SapphCooking.BowlofTortellini:7;SapphCooking.BowlofBeefStew:7;SapphCooking.BowlofRefriedBeans:7;SapphCooking.BowlofSpaguetti:7;SapphCooking.BowlofSpaguettiandMeatballs:7;SapphCooking.BowlofMashedPotatoes:7;SapphCooking.BowlofYakisoba:7;SapphCooking.BowlofKungPaoChicken:7;SapphCooking.BowlofShuiZhuYu:7;SapphCooking.BowlofJapaneseCurry:7;SapphCooking.BowlofBorscht:7;SapphCooking.BowlofMashedPotatoes_Meatballs:7;SapphCooking.BowlofRiceJapaneseCurry:7;SapphCooking.FryingPan_BaconandEggs:7;SapphCooking.Plate_BaconandEggs:7;SapphCooking.PlateBlue_BaconandEggs:7;SapphCooking.PlateOrange_BaconandEggs:7;SapphCooking.PlateFancy_BaconandEggs:7;SapphCooking.RiceBeanBowl:7;SapphCooking.BowlofChickenStroganoff:7;SapphCooking.BowlofRiceChickenStroganoff:7;SapphCooking.Plate_HuevosRancheros:7;SapphCooking.PlateBlue_HuevosRancheros:7;SapphCooking.PlateOrange_HuevosRancheros:7;SapphCooking.PlateFancy_HuevosRancheros:7;SapphCooking.PoutineBowl:7;SapphCooking.SkewersInsect:5;SapphCooking.SkewersMeat:5;SapphCooking.SkewersVegetable:5;SapphCooking.SapphCrackers:5;SapphCooking.SapphCrackers2:5;SapphCooking.BakedPotatoEvolved:5;SapphCooking.FriedRiceWok:5")
	end

	
	local item = ScriptManager.instance:getItem("SapphCooking.CurryPowder")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:2;SapphCooking.LettuceWrapEvolved:2;SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.CocktailMix:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2;SapphCooking.BakedPotatoEvolved:2;SapphCooking.FriedRiceWok:2")
	end
	

	local item = ScriptManager.instance:getItem("SapphCooking.HotsaucePacket")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:2;SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.CocktailMix:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2;SapphCooking.BakedPotatoEvolved:2;SapphCooking.FriedRiceWok:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.MonosodiumGlutamate_MSG")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:2;SapphCooking.LettuceWrapEvolved:2;SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.CocktailMix:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2;SapphCooking.BakedPotatoEvolved:2;SapphCooking.FriedRiceWok:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Spice_Furikake")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:2;SapphCooking.LettuceWrapEvolved:2;SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.CocktailMix:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2;SapphCooking.BakedPotatoEvolved:2;SapphCooking.FriedRiceWok:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Spice_OysterSauce")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:2;SapphCooking.LettuceWrapEvolved:2;SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.CocktailMix:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2;SapphCooking.BakedPotatoEvolved:2;SapphCooking.FriedRiceWok:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Spice_PestoBowl")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:2;SapphCooking.LettuceWrapEvolved:2;SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.CocktailMix:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2;SapphCooking.BakedPotatoEvolved:2;SapphCooking.FriedRiceWok:2")
	end
	
	

	local item = ScriptManager.instance:getItem("SapphCooking.Tomato_Sachet")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:2;SapphCooking.LettuceWrapEvolved:2;SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.CocktailMix:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2;SapphCooking.BakedPotatoEvolved:2;SapphCooking.FriedRiceWok:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.SoySauce_Sachet")
	if item then

		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:2;SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2;SapphCooking.FriedRiceWok:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Mustard_Sachet")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:2;SapphCooking.LettuceWrapEvolved:2;SapphCooking.CornCob:2;SapphCooking.CrepesEvolved:2;SapphCooking.FlatbreadEvolved:2;SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.SushiEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.SapphCrackers:2;SapphCooking.SapphCrackers2:2;SapphCooking.FriedRiceWok:2")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.Jar_Kimchi_Fermented")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:2;SapphCooking.LettuceWrapEvolved:2;SapphCooking.CornCob:4;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;Pizza:8;Omelette:8;Soup:8;Stew:8;Stir fry Griddle Pan:8;Stir fry:8;Burger:8;Salad:8;Roasted Vegetables:8;RicePot:8;RicePan:8;PastaPot:8;PastaPan:8;Sandwich:8;Sandwich Baguette:8;Taco:8;Burrito:8;SapphCooking.MRE_1:8;SapphCooking.MRE_2:8;SapphCooking.MRE_3:8;SapphCooking.MRE_4:8;SapphCooking.MRE_5:8;SapphCooking.MRE_6:8;SapphCooking.MRE_7:8;SapphCooking.MRE_8:8;SapphCooking.MRE_9:8;SapphCooking.MRE_10:8;SapphCooking.MRE_11:8;SapphCooking.MRE_12:8;SapphCooking.BowlofFriedRice:8;SapphCooking.BowlofOmurice:8;SapphCooking.ArborioRiceBowl:8;SapphCooking.BowlofRisotto:8;SapphCooking.BrownRiceBowl:8;SapphCooking.BowlofRavioli:8;SapphCooking.BowlofTortellini:8;SapphCooking.BowlofBeefStew:8;SapphCooking.BowlofRefriedBeans:8;SapphCooking.BowlofSpaguetti:8;SapphCooking.BowlofSpaguettiandMeatballs:8;SapphCooking.BowlofMashedPotatoes:8;SapphCooking.BowlofYakisoba:8;SapphCooking.BowlofKungPaoChicken:8;SapphCooking.BowlofShuiZhuYu:8;SapphCooking.BowlofJapaneseCurry:8;SapphCooking.BowlofBorscht:8;SapphCooking.BowlofMashedPotatoes_Meatballs:8;SapphCooking.BowlofRiceJapaneseCurry:8;SapphCooking.FryingPan_BaconandEggs:8;SapphCooking.Plate_BaconandEggs:8;SapphCooking.PlateBlue_BaconandEggs:8;SapphCooking.PlateOrange_BaconandEggs:8;SapphCooking.PlateFancy_BaconandEggs:8;SapphCooking.RiceBeanBowl:8;SapphCooking.BowlofChickenStroganoff:8;SapphCooking.BowlofRiceChickenStroganoff:8;SapphCooking.Plate_HuevosRancheros:8;SapphCooking.PlateBlue_HuevosRancheros:8;SapphCooking.PlateOrange_HuevosRancheros:8;SapphCooking.PlateFancy_HuevosRancheros:8;SapphCooking.PoutineBowl:8;SapphCooking.SapphCrackers:8;SapphCooking.SapphCrackers2:8;SapphCooking.FriedRiceWok:8")
	end

	local item = ScriptManager.instance:getItem("SapphCooking.MisoPaste")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.StuffedPepperEvolved:2;SapphCooking.LettuceWrapEvolved:2;SapphCooking.CornCob:4;SapphCooking.CrepesEvolved:8;SapphCooking.FlatbreadEvolved:8;SapphCooking.WokRoastVeg:8;SapphCooking.HR1:8;SapphCooking.HR2:8;SapphCooking.HR3:8;SapphCooking.HR4:8;SapphCooking.InstantNoodles:8;SapphCooking.FryingPanwithFriedRice:8;SapphCooking.SpringrollEvolved:8;SapphCooking.PoutineEvolved:8;SapphCooking.CevicheEvolved:8;SapphCooking.SausageEvolved:8;SapphCooking.DumplingsEvolved:8;SapphCooking.HotdogSandwich:8;SapphCooking.HotdogEvolved:8;SapphCooking.SushiEvolved:8;SapphCooking.YakisobaEvolved:8;SapphCooking.RatatouilleEvolved:8;SapphCooking.LasagnaEvolved:8;Pizza:8;Omelette:8;Soup:8;Stew:8;Stir fry Griddle Pan:8;Stir fry:8;Burger:8;Salad:8;Roasted Vegetables:8;RicePot:8;RicePan:8;PastaPot:8;PastaPan:8;Sandwich:8;Sandwich Baguette:8;Taco:8;Burrito:8;SapphCooking.MRE_1:8;SapphCooking.MRE_2:8;SapphCooking.MRE_3:8;SapphCooking.MRE_4:8;SapphCooking.MRE_5:8;SapphCooking.MRE_6:8;SapphCooking.MRE_7:8;SapphCooking.MRE_8:8;SapphCooking.MRE_9:8;SapphCooking.MRE_10:8;SapphCooking.MRE_11:8;SapphCooking.MRE_12:8;SapphCooking.BowlofFriedRice:8;SapphCooking.BowlofOmurice:8;SapphCooking.ArborioRiceBowl:8;SapphCooking.BowlofRisotto:8;SapphCooking.BrownRiceBowl:8;SapphCooking.BowlofRavioli:8;SapphCooking.BowlofTortellini:8;SapphCooking.BowlofBeefStew:8;SapphCooking.BowlofRefriedBeans:8;SapphCooking.BowlofSpaguetti:8;SapphCooking.BowlofSpaguettiandMeatballs:8;SapphCooking.BowlofMashedPotatoes:8;SapphCooking.BowlofYakisoba:8;SapphCooking.BowlofKungPaoChicken:8;SapphCooking.BowlofShuiZhuYu:8;SapphCooking.BowlofJapaneseCurry:8;SapphCooking.BowlofBorscht:8;SapphCooking.BowlofMashedPotatoes_Meatballs:8;SapphCooking.BowlofRiceJapaneseCurry:8;SapphCooking.FryingPan_BaconandEggs:8;SapphCooking.Plate_BaconandEggs:8;SapphCooking.PlateBlue_BaconandEggs:8;SapphCooking.PlateOrange_BaconandEggs:8;SapphCooking.PlateFancy_BaconandEggs:8;SapphCooking.RiceBeanBowl:8;SapphCooking.BowlofChickenStroganoff:8;SapphCooking.BowlofRiceChickenStroganoff:8;SapphCooking.Plate_HuevosRancheros:8;SapphCooking.PlateBlue_HuevosRancheros:8;SapphCooking.PlateOrange_HuevosRancheros:8;SapphCooking.PlateFancy_HuevosRancheros:8;SapphCooking.PoutineBowl:8;SapphCooking.SapphCrackers:8;SapphCooking.SapphCrackers2:8;SapphCooking.FriedRiceWok:8")
	end

	


	--Oils
	local item = ScriptManager.instance:getItem("SapphCooking.PeanutOil")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.CornCob:2;SapphCooking.WokRoastVeg:2;SapphCooking.BlenderShake:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.SpringrollEvolved:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.SausageEvolved:2;SapphCooking.DumplingsEvolved:2;SapphCooking.HotdogSandwich:2;SapphCooking.HotdogEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.SkewersInsect:2;SapphCooking.SkewersMeat:2;SapphCooking.SkewersVegetable:2;SapphCooking.BakedPotatoEvolved:2;SapphCooking.FriedRiceWok:2")
	end

	--bread
	local item = ScriptManager.instance:getItem("SapphCooking.Flatbread")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.FriedRiceWok:2")
	end
	local item = ScriptManager.instance:getItem("SapphCooking.FlatbreadEvolved")
	if item then
		item:DoParam("EvolvedRecipe = SapphCooking.WokRoastVeg:2;SapphCooking.HR1:2;SapphCooking.HR2:2;SapphCooking.HR3:2;SapphCooking.HR4:2;SapphCooking.InstantNoodles:2;SapphCooking.FryingPanwithFriedRice:2;SapphCooking.PoutineEvolved:2;SapphCooking.CevicheEvolved:2;SapphCooking.YakisobaEvolved:2;SapphCooking.RatatouilleEvolved:2;SapphCooking.LasagnaEvolved:2;Pizza:2;Omelette:2;Soup:2;Stew:2;Pie:2;Stir fry Griddle Pan:2;Stir fry:2;Burger:1;Salad:2;Roasted Vegetables:2;RicePot:2;RicePan:2;PastaPot:2;PastaPan:2;Sandwich:2;Sandwich Baguette:2;Taco:2;Burrito:2;SapphCooking.MRE_1:3;SapphCooking.MRE_2:3;SapphCooking.MRE_3:3;SapphCooking.MRE_4:3;SapphCooking.MRE_5:3;SapphCooking.MRE_6:3;SapphCooking.MRE_7:3;SapphCooking.MRE_8:3;SapphCooking.MRE_9:3;SapphCooking.MRE_10:3;SapphCooking.MRE_11:3;SapphCooking.MRE_12:3;SapphCooking.BowlofFriedRice:3;SapphCooking.BowlofOmurice:3;SapphCooking.ArborioRiceBowl:3;SapphCooking.BowlofRisotto:3;SapphCooking.BrownRiceBowl:3;SapphCooking.BowlofRavioli:3;SapphCooking.BowlofTortellini:3;SapphCooking.BowlofBeefStew:3;SapphCooking.BowlofRefriedBeans:3;SapphCooking.BowlofSpaguetti:3;SapphCooking.BowlofSpaguettiandMeatballs:3;SapphCooking.BowlofMashedPotatoes:3;SapphCooking.BowlofYakisoba:3;SapphCooking.BowlofKungPaoChicken:3;SapphCooking.BowlofShuiZhuYu:3;SapphCooking.BowlofJapaneseCurry:3;SapphCooking.BowlofBorscht:3;SapphCooking.BowlofMashedPotatoes_Meatballs:3;SapphCooking.BowlofRiceJapaneseCurry:3;SapphCooking.FryingPan_BaconandEggs:3;SapphCooking.Plate_BaconandEggs:3;SapphCooking.PlateBlue_BaconandEggs:3;SapphCooking.PlateOrange_BaconandEggs:3;SapphCooking.PlateFancy_BaconandEggs:3;SapphCooking.RiceBeanBowl:3;SapphCooking.BowlofChickenStroganoff:3;SapphCooking.BowlofRiceChickenStroganoff:3;SapphCooking.Plate_HuevosRancheros:3;SapphCooking.PlateBlue_HuevosRancheros:3;SapphCooking.PlateOrange_HuevosRancheros:3;SapphCooking.PlateFancy_HuevosRancheros:3;SapphCooking.PoutineBowl:3;SapphCooking.FriedRiceWok:2")
	end

end


CustomTweakRecipes()
Events.OnInitGlobalModData.Add(CustomTweakRecipes)
