require 'Items/SuburbsDistributions'
require 'Items/ProceduralDistributions'

table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 4);
table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);
table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);
table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);
table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);
table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);
table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);

table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);
table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);
table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);
table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);
table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);
table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);
table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);

table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 10);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 10);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 10);

table.insert(ProceduralDistributions.list["MotelFridge"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["MotelFridge"].items, 10);
table.insert(ProceduralDistributions.list["MotelFridge"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["MotelFridge"].items, 10);

table.insert(ProceduralDistributions.list["StoreShelfDrinks"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["StoreShelfDrinks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfDrinks"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["StoreShelfDrinks"].items, 10);

table.insert(ProceduralDistributions.list["TheatreDrinks"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["TheatreDrinks"].items, 10);
table.insert(ProceduralDistributions.list["TheatreDrinks"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["TheatreDrinks"].items, 10);

table.insert(ProceduralDistributions.list["KitchenBottles"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["KitchenBottles"].items, 10);
table.insert(ProceduralDistributions.list["KitchenBottles"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["KitchenBottles"].items, 10);
 
table.insert(ProceduralDistributions.list["FridgeOffice"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["FridgeOffice"].items, 10);
table.insert(ProceduralDistributions.list["FridgeOffice"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["FridgeOffice"].items, 10);
table.insert(ProceduralDistributions.list["FridgeOffice"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["FridgeOffice"].items, 10);
table.insert(ProceduralDistributions.list["FridgeOffice"].items, "stalkerfood.StalkerEnergyDrink");
table.insert(ProceduralDistributions.list["FridgeOffice"].items, 10);

table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);
table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);
table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);

table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);
table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);
table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);
table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);
table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);
table.insert(ProceduralDistributions.list["FridgeSoda"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["FridgeSoda"].items, 10);

table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);
table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);
table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);
table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);
table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);
table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);
table.insert(ProceduralDistributions.list["GigamartBottles"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["GigamartBottles"].items, 10);

table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 10);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 10);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 10);

table.insert(ProceduralDistributions.list["MotelFridge"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["MotelFridge"].items, 10);
table.insert(ProceduralDistributions.list["MotelFridge"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["MotelFridge"].items, 10);

table.insert(ProceduralDistributions.list["StoreShelfDrinks"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["StoreShelfDrinks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfDrinks"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["StoreShelfDrinks"].items, 10);

table.insert(ProceduralDistributions.list["TheatreDrinks"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["TheatreDrinks"].items, 10);
table.insert(ProceduralDistributions.list["TheatreDrinks"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["TheatreDrinks"].items, 10);

table.insert(ProceduralDistributions.list["KitchenBottles"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["KitchenBottles"].items, 10);
table.insert(ProceduralDistributions.list["KitchenBottles"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["KitchenBottles"].items, 10);

table.insert(ProceduralDistributions.list["BarShelfLiquor"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["BarShelfLiquor"].items, 10);
table.insert(ProceduralDistributions.list["BarShelfLiquor"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["BarShelfLiquor"].items, 10);

table.insert(ProceduralDistributions.list["StoreShelfWhiskey"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["StoreShelfWhiskey"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfWhiskey"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["StoreShelfWhiskey"].items, 10);

table.insert(ProceduralDistributions.list["StoreShelfWine"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["StoreShelfWine"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfWine"].items, "stalkerfood.CossacksVodka");
table.insert(ProceduralDistributions.list["StoreShelfWine"].items, 10);

table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);

table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);

table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.TouristsDelight");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);

table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);

table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);

table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.CannedBeef");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);

table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 10);

table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 10);

table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.OldMeat");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);

table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 1);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 1);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 2);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 3);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 1);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 3);
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["KitchenCannedFood"].items, 5);

table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 2);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 2);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 1);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 5);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 1);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 5);
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["GigamartCannedFood"].items, 2);

table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 1);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 4);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 3);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 3);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 1);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 3);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.DietSausage");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 2);

table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, 10);
table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, 10);
table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, 10);
table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, 10);
table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, 10);
table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, 10);
table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["CandyStoreSnacks"].items, 10);

table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);

table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.Altoids");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 10);

table.insert(ProceduralDistributions.list["CrateCannedFood"].items, "stalkerfood.MRE");
table.insert(ProceduralDistributions.list["CrateCannedFood"].items, 1);
table.insert(ProceduralDistributions.list["CrateCannedFood"].items, "stalkerfood.MRE");
table.insert(ProceduralDistributions.list["CrateCannedFood"].items, 1);
table.insert(ProceduralDistributions.list["CrateCannedFood"].items, "stalkerfood.MRE");
table.insert(ProceduralDistributions.list["CrateCannedFood"].items, 1);
table.insert(ProceduralDistributions.list["CrateCannedFood"].items, "stalkerfood.MRE");
table.insert(ProceduralDistributions.list["CrateCannedFood"].items, 1);

table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.MRE");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 1);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.MRE");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 1);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.MRE");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 1);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.MRE");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 1);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.MRE");

table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.MRE");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 1);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.MRE");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 1);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.MRE");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 1);
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, "stalkerfood.MRE");
table.insert(ProceduralDistributions.list["StoreShelfSnacks"].items, 1);

table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.MarlboroCigarettes");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 3);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.MarlboroCigarettes");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 3);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.MarlboroCigarettes");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 3);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.MarlboroCigarettes");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 3);

table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.MarlboroCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.MarlboroCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.MarlboroCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.MarlboroCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.MarlboroCigarettes");

table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.MarlboroCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.MarlboroCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.MarlboroCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.MarlboroCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);

table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.RussianBrandCigarettes");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 3);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.RussianBrandCigarettes");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 3);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.RussianBrandCigarettes");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 3);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.RussianBrandCigarettes");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 3);

table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.RussianBrandCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.RussianBrandCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.RussianBrandCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.RussianBrandCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.RussianBrandCigarettes");

table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.RussianBrandCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.RussianBrandCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.RussianBrandCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.RussianBrandCigarettes");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);

table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.HandRollingTobacco");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 3);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.HandRollingTobacco");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 3);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.HandRollingTobacco");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 3);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.HandRollingTobacco");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 3);

table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.HandRollingTobacco");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.HandRollingTobacco");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.HandRollingTobacco");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.HandRollingTobacco");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.HandRollingTobacco");

table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.HandRollingTobacco");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.HandRollingTobacco");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.HandRollingTobacco");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.HandRollingTobacco");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 3);

table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.CubanCigar");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 1);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.CubanCigar");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 1);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.CubanCigar");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 1);
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, "stalkerfood.CubanCigar");
table.insert(ProceduralDistributions.list["BarCounterMisc"].items, 1);

table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.CubanCigar");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 1);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.CubanCigar");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 1);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.CubanCigar");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 1);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.CubanCigar");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 1);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.CubanCigar");

table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.CubanCigar");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 1);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.CubanCigar");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 1);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.CubanCigar");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 1);
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, "stalkerfood.CubanCigar");
table.insert(ProceduralDistributions.list["StoreCounterTobacco"].items, 1);
